# suppress inspection "UnusedProperty" for whole file

spring.application.name=propertiesApp

server.port=3333
spring.datasource.url=jdbc:postgresql://localhost:5432/ourlisting
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
logging.level.root=INFO


spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
server.tomcat.max-swallow-size=100MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=subscriberch03@gmail.com
spring.mail.password=lvxsmrqvotxumwbm
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
mail.smtp.connectiontimeout=30000
mail.smtp.timeout=60000
spring.mail.properties.mail.debug=true

# Livereload
spring.devtools.livereload.enabled=true

secret.key=SmXhmb3JdHFjsCDRfiv0yXE0ngiJfatIiYpCJUoObLE=
baseurl.web=https://propertyapp.ddns.net

#Reverse Geocoding API
geocode.uri=https://geocode.maps.co/reverse
geocode.key=66baeaf036bae960511061las2d2e4a

#CLoudinary Image Services
cloudinary.cloud-name=dvp0fow8r
cloudinary.api-key=933729314869176
cloudinary.api-secret=u1osHTN8mLeppa-94qRxuC1HoVA

#Filestack
aws.region=ap-south-1
aws.bucketName=croscrowtest

#PayPal
paypal.client.id=AU_x28CA0S8MZd_gVFL-a3tKjbvhbfFLnrq6ObvoqsaFbewauWuUyWJjpXu3ChFJKw_JTkOpQLLPFRDH
paypal.client.secret=EEddpsBbhUzWat_Ox-f5NA7FY0eoKVSAlzF8P-vlA9H4aJupAeZMZBw0pme64JMIwdU1TVUkoMlMQghO
paypal.mode=sandbox
