spring.application.name=propertiesApp

server.port=3123
spring.datasource.url=jdbc:postgresql://localhost:5432/propertiesApp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
#logging.level.root=DEBUG

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
server.tomcat.max-swallow-size=100MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=subscriberch03@gmail.com
spring.mail.password=lvxsmrqvotxumwbm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.debug=true
mail.smtp.keepalive=true
mail.smtp.connectiontimeout=30000
mail.smtp.timeout=60000

# Livereload
spring.devtools.livereload.enabled=true

secret.key=SmXhmb3JdHFjsCDRfiv0yXE0ngiJfatIiYpCJUoObLE=

#Reverse Geocoding API
geocode.uri=https://geocode.maps.co/reverse
geocode.key=66baeaf036bae960511061las2d2e4a

#CLoudinary Image Services
cloudinary.cloud-name=dvp0fow8r
cloudinary.api-key=933729314869176
cloudinary.api-secret=u1osHTN8mLeppa-94qRxuC1HoVA

#Filestack
filestack.key=AuG6Zsd5MS3mwCka2ZF50z

#PayPal
paypal.client.id=ASSOxr6AzL6YalQFmeludpEjc_0I5-6yaqaj3gfwE89Z_ePfgWm83tVdHY_RZYA549FUrCG-6RehK8s9
paypal.client.secret=EFTix1_wn2xV7l6UlNHNxbGfYNKDXwhLamdxdmI6vl1mPo3BZnBYIcLv-SYkpIfxU3iciY7BoPbZdZpy
paypal.mode=sandbox
